services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
    environment:
      - DB_TYPE=postgres
      - DB_HOST=uptime-kuma-db.cj24eucoaq0n.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USER=uptimekuma
      - DB_NAME=uptimekuma
      - DB_PASSWORD=${DB_PASSWORD}
